AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions an EC2 instance in an Auto Scaling Group bootstrapped to snapshot EBS volumes once a day and retain snapshots for 14 days
Parameters:
  InstanceType:
    Description: Desired instance type for EC2 instance used for EBS management cron jobs
    Type: String
    Default: t2.micro
  CentOS7AmiId:
    Description: ID of preferred AMI (UserData assumes CentOS 7)
    Type: String
  SshKey:
    Description: The name of the key pair to be used to SSH into EC2 instance
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
  SecurityGroupId:
    Description: The ID of an existing security group in the current region
    Type: AWS::EC2::SecurityGroup::Id
    ConstraintDescription: Must be the ID of an existing VPC in the format sg-xxxxxxxx
Resources:
  EbsBkupRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  EbsBkupPolicy: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "EbsBkupPolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action:
              - "ec2:DescribeSnapshots"
              - "ec2:CreateSnapshot"
              - "ec2:DeleteSnapshot"
            Resource:
              Fn::Join:
                - ":"
                - - "arn"
                  - "aws"
                  - "ec2"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - "snapshot/*"
          - Effect: "Allow"
            Action:
              - "ec2:DescribeVolumes"
            Resource:
              Fn::Join:
                - ":"
                - - "arn"
                  - "aws"
                  - "ec2"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - "volume/*"
      Roles: 
        - Ref: "EbsBkupRole"
  EbsBkupInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - Ref: "EbsBkupRole"
  LaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      IamInstanceProfile: !GetAtt EbsBkupInstanceProfile.Arn
      ImageId: !Ref CentOS7AmiId
      InstanceMonitoring: "false"
      InstanceType: !Ref InstanceType
      KeyName: !Ref SshKey
      SecurityGroups: 
        - Ref: SecurityGroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |     # No more Fn::Join needed
          #!/bin/bash
          yum install epel-release -y
          yum install jq python-pip -y
          pip install --upgrade --user awscli
          ln -s /root/.local/bin/aws /usr/bin/aws
          aws configure set output json
          aws configure set region ${AWS::Region}
  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AvailabilityZones:
        Fn::GetAZs:
          Ref: "AWS::Region"
      LaunchConfigurationName: !Ref LaunchConfiguration
      DesiredCapacity: "1"
      MaxSize: "1"
      MinSize: "1"
      Tags:
        - Key: Name
          Value: EBS Backup HA Instance
          PropagateAtLaunch: true
        - Key: Purpose
          Value: Ensures high availability
          PropagateAtLaunch: false
Outputs:
  LaunchConfigurationId:
    Description: The ID of the Launch Configuration
    Value:
      Ref: "LaunchConfiguration"
  AutoScalingGroupId:
    Description: The ID of the Auto Scaling Group
    Value:
      Ref: "AutoScalingGroup"
  EbsBkupRoleId:
    Description: The ID of the Role
    Value:
      Ref: "EbsBkupRole"
  EbsBkupPolicyId:
    Description: The ID of the Policy
    Value:
      Ref: "EbsBkupPolicy"
  EbsBkupInstanceProfileId:
    Description: The ID of the Instance Profile
    Value:
      Ref: "EbsBkupInstanceProfile"